DROP TABLE IF EXISTS ref_organization CASCADE;

create table if not exists ref_organization
(
    id                 uuid primary key,
    parent             uuid,
    is_group           boolean,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    changed_at         TIMESTAMP WITHOUT TIME ZONE,
    name               varchar(150),
    full_name          varchar(150),
    is_marked_deletion boolean,
    number             integer generated by default as identity,
    owner_organization uuid,
    inn                varchar(15),
    kpp                varchar(15)

);

INSERT INTO public.ref_organization
(id, parent, is_group, created_at, changed_at, name, full_name, is_marked_deletion,
 owner_organization, inn, kpp)
VALUES ('31111111-1111-1111-1111-111111111111', null, false, '2024-06-08 12:05:18.000000',
        '2024-06-08 12:05:21.000000', 'orgadmin', 'orgadmin', false, '11111111-1111-1111-1111-111111111111',
        '3527935566', '311065368'),
       ('31111111-1111-1111-1111-111111111112', null, false, '2024-06-08 12:05:18.000000',
        '2024-06-08 12:05:21.000000', 'org1', 'Organization One', false, '11111111-1111-1111-1111-111111111112',
        '3527935567', '311065369'),
       ('31111111-1111-1111-1111-111111111113', null, false, '2024-06-08 12:05:18.000000',
        '2024-06-08 12:05:21.000000', 'org2', 'Organization Two', false, '11111111-1111-1111-1111-111111111113',
        '3527935568', '311065370'),
       ('31111111-1111-1111-1111-111111111114', null, false, '2024-06-08 12:05:18.000000',
        '2024-06-08 12:05:21.000000', 'org3', 'Organization Three', false, '11111111-1111-1111-1111-111111111114',
        '3527935569', '311065371'),
       ('31111111-1111-1111-1111-111111111115', null, false, '2024-06-08 12:05:18.000000',
        '2024-06-08 12:05:21.000000', 'org4', 'Organization Four', false, '11111111-1111-1111-1111-111111111115',
        '3527935570', '311065372');

alter table ref_organization
    add constraint ref_organization_ref_organization_id_fk
        foreign key (parent) references ref_organization (id);

