DROP TABLE IF EXISTS ref_accounts CASCADE;
DROP TABLE IF EXISTS ref_organization CASCADE;

create table if not exists ref_organization
(
    id                 uuid primary key,
    parent             uuid,
    is_group           boolean,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    changed_at         TIMESTAMP WITHOUT TIME ZONE,
    author_id          uuid,
    change_id          uuid,
    name               varchar(150),
    full_name          varchar(150),
    is_marked_deletion boolean,
    number             integer generated by default as identity,
    owner_organization uuid,
    inn                varchar(15),
    kpp                varchar(15)

);

create table if not exists ref_accounts
(
    id                 uuid                                                  not null
        constraint ref_accounts_pk
            primary key,
    firstname          varchar(50)                                           not null,
    middlename         varchar(50),
    lastname           varchar(50),
    email              varchar(100),
    birthday           date,
    phone              varchar(25),
    created_at         TIMESTAMP WITHOUT TIME ZONE default CURRENT_TIMESTAMP not null,
    updated_at         TIMESTAMP WITHOUT TIME ZONE default CURRENT_TIMESTAMP,
    author_id          uuid                                                  not null,
    change_id          uuid,
    status             varchar(50)                                           not null,
    is_group           boolean                                               not null,
    login              varchar(50),
    password           varchar(50),
    is_marked_deletion boolean                                               not null,
    parent             uuid,
    owner_organization uuid                                                  not null
);

alter table ref_accounts
    owner to postgres;

INSERT INTO public.ref_organization
(id, parent, is_group, created_at, changed_at, author_id, change_id, name, full_name, is_marked_deletion,
 owner_organization, inn, kpp)
VALUES ('11111111-1111-1111-1111-111111111111', null, false, '2024-06-08 12:05:18.000000',
        '2024-06-08 12:05:21.000000', '11111111-1111-1111-1111-111111111111',
        '11111111-1111-1111-1111-111111111111', 'orgadmin', 'orgadmin', false, '11111111-1111-1111-1111-111111111111',
        '3527935566', '311065368');

INSERT INTO public.ref_accounts (id, firstname, middlename, lastname, email, birthday, phone,
                                 created_at, updated_at, author_id, change_id,
                                 status, is_marked_deletion, parent, owner_organization, is_group)
VALUES ('11111111-1111-1111-1111-111111111111', 'admin', 'admin', 'admin', 'admin@yandex.ru',
        '2024-06-08', '+79379377979', '2024-06-08 12:08:00.000000', '2024-06-08 12:08:02.000000',
        '11111111-1111-1111-1111-111111111111', '11111111-1111-1111-1111-111111111111',
        'ACTIVE', false, null, '11111111-1111-1111-1111-111111111111', false);

INSERT INTO public.ref_accounts (id, firstname, middlename, lastname, email, birthday, phone,
                                 created_at, updated_at, author_id, change_id,
                                 status, is_marked_deletion, parent, owner_organization, is_group)
VALUES ('21111111-1111-1111-1111-111111111111', 'admin2', 'admin2', 'admin2', 'admin@yandex.ru',
        '2024-06-08', '+79379377979', '2024-06-08 12:08:00.000000', '2024-06-08 12:08:02.000000',
        '11111111-1111-1111-1111-111111111111', '11111111-1111-1111-1111-111111111111',
        'ACTIVE', false, null, '11111111-1111-1111-1111-111111111111', false);

alter table ref_organization
    add constraint ref_organization_ref_accounts_id_fk
        foreign key (author_id) references ref_accounts (id);

alter table ref_organization
    add constraint ref_organization_ref_accounts_id_fk_2
        foreign key (change_id) references ref_accounts (id);

alter table ref_organization
    add constraint ref_organization_ref_organization_id_fk
        foreign key (parent) references ref_organization (id);

alter table ref_accounts
    add constraint ref_accounts_ref_organization_id_fk
        foreign key (owner_organization) references ref_organization (id);
