DROP TABLE IF EXISTS ref_accounts, ref_organization;

create table if not exists ref_organization
(
    id                 uuid         default gen_random_uuid()                 not null,
    parent             uuid,
    is_group           boolean      default false                             not null,
    created_at         timestamp    default now()                             not null,
    changed_at         timestamp    default now(),
    author_id          uuid                                                   not null,
    change_id          uuid,
    name               varchar(150) default 'Наименование'::character varying not null,
    is_marked_deletion boolean      default false                             not null,
    number             integer generated by default as identity,
    constraint ref_organization_pk
        primary key (id)

);

create table ref_accounts
(
    id                 uuid      default gen_random_uuid() not null
        constraint ref_accounts_pk
            primary key,
    firstname          varchar(50)                         not null,
    middlename         varchar(50),
    lastname           varchar(50),
    email              varchar(100),
    birthday           date,
    phone              varchar(25),
    created_at         timestamp default now()             not null,
    updated_at         timestamp default now(),
    author_id          uuid                                not null
        constraint ref_accounts_ref_accounts_id_fk_2
            references ref_accounts
            on delete set null,
    change_id          uuid
        constraint ref_accounts_ref_accounts_id_fk
            references ref_accounts
            on delete set null,
    status             varchar(50)                         not null,
    is_marked_deletion boolean   default false             not null,
    parent             uuid
        constraint ref_accounts_ref_accounts_id_fk_3
            references ref_accounts
);

alter table ref_accounts
    owner to postgres;

INSERT INTO public.ref_organization
(id, parent, is_group, created_at, changed_at, author_id, change_id, name, is_marked_deletion)
VALUES ('11111111-1111-1111-1111-111111111111', null, false, '2024-06-08 12:05:18.000000',
        '2024-06-08 12:05:21.000000', '11111111-1111-1111-1111-111111111111',
        '11111111-1111-1111-1111-111111111111', 'orgadmin', false);

INSERT INTO public.ref_accounts (id, firstname, middlename, lastname, email, birthday, phone,
                                 created_at, updated_at, author_id, change_id,
                                 status, is_marked_deletion, parent)
VALUES ('11111111-1111-1111-1111-111111111111', 'admin', 'admin', 'admin', 'admin@yandex.ru',
        '2024-06-08', '+79379377979', '2024-06-08 12:08:00.000000', '2024-06-08 12:08:02.000000',
        '11111111-1111-1111-1111-111111111111', '11111111-1111-1111-1111-111111111111',
        'ACTIVATED', false, null);

alter table ref_organization
    add constraint ref_organization_ref_accounts_id_fk
        foreign key (author_id) references ref_accounts;

alter table ref_organization
    add constraint ref_organization_ref_accounts_id_fk_2
        foreign key (change_id) references ref_accounts;

alter table ref_organization
    add constraint ref_organization_ref_organization_id_fk
        foreign key (parent) references ref_organization;